pipeline {
    agent any

    tools {
        maven 'Maven'  // This must match the name you gave to your Maven installation
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                script {
                    // Run Maven clean install to build the project
                    sh 'mvn clean install'
                }
            }
        }
    }
}

