pipeline {
    agent any

    tools {
        jdk 'jdk17'         // Make sure this matches the name in Global Tool Config
        maven 'Maven'       // Should also match what you configured
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build JAR') {
            steps {
                dir('project-16') {
                    sh 'mvn clean install'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("tanya119/project16-app:latest", 'project-16/')
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    withDockerRegistry([credentialsId: '51611545-1f09-453a-a2a6-e0120a9347f2', url: '']) {
                        dockerImage.push()
                    }
                }
            }
        }
    }
}




